# 配置文件

# 功能：给女朋友发早安和土味情话
loveMsg:
  # 与女朋友相识的日子
  start_stamp: 2022-01-13
  # 女朋友所在城市（不要带‘市’）
  locationid: 101270608
  city_name: 达州
  # 对女朋友的爱称
  girl_name: 小兔几
  # 对自己的称呼
  boy_name: 大兔几
  # 点击卡片详情地址
  card_url: https://baotangguo.cn:8081/
  # 天气生活指数提示（默认开启）
  weather_tips: true
  # 极端天气温度提醒（默认开启）
  # 卡片内容字节限制可能显示不完全
  weather_tem: true
  # 农历信息（默认开启）
  date_lunarInfo: true
  weather_figure_type: 0
